apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /courses
spec:
  ingressClassName: nginx
  rules:
    - host: goapp.com
      http:
        paths:
          - path: /courses
            pathType: Prefix
            backend:
              service:
                name: go-web-app-service
                port:
                  number: 80
