apiVersion: v1
kind: Service

metadata:
  name: go-web-app-service

spec:
  type: LoadBalancer
  selector:
    app: go-web-app

  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 8080  # Container port
      nodePort: 30007   # Optional (30000â€“32767)
