replicaCount: 3

app:
  name: go-web-app

image:
  repository: azizaman/go-web-app
  tag: "e7800b6dbd9cec05ae4806c45d2241f748532dcd"
  pullPolicy: IfNotPresent

containerPort: 8080
service:
  type: ClusterIP
  protocol: TCP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  className: nginx
  path: /courses
  pathType: Prefix
  rewriteTarget: /courses

